# Generated by Django 5.0.2 on 2024-02-25 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_crawler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='addresss',
            new_name='address',
        ),
    ]
