# Generated by Django 5.0.2 on 2024-02-22 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Musics',
            new_name='Music',
        ),
    ]
